# Basic
title: 清风君
subtitle: 我本一缕清风，逍遥天地间
welcome_message: 欢迎来到清风君的世界
description: 分享技术，分享生活
creator: <a href="#">@清风君</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog列表
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/qingfengjun/qingfengjun.github.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

categeries:
    - {title: 技术, description: 技术, url: '/category/jishu/index.html'}
    - {title: 随笔, description: 随笔, url: '/category/suibi/index.html'}
    - {title: 照片, description: 照片, url: '/category/zhaopian/index.html'}
    - {title: 生活, description: 生活, url: '/category/shenghuo/index.html'}
    - {title: 收集, description: 收集, url: '/category/shouji/index.html'}
# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment 这是disqus的评论系统
comment:
    disqus: abbott-king
    # duoshuo: 
    
# Social

social:
    weibo: https://www.cnblogs.com/xiaoshuai1992/
    github: qingfengjun
    mail: xshuai1992@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

leancloud:
  enable: true
  app_id: n9H2t3VFwwMPqC0rSYfvlJuu-gzGzoHsz
  app_key: DkeWUHsd9YIYIsnKRg6vw1Lk